const mongoose = require("mongoose");
require("dotenv").config();
const Book = require("./models/Book");

mongoose.connect(process.env.MONGO_URI);

const books = [
  // ─── Fiction ───────────────────────────────────────────────
  {
    title: "The Alchemist",
    author: "Paulo Coelho",
    price: 399,
    description: "A magical fable about following your dreams, from the shepherd Santiago's journey across the Egyptian desert to find a worldly treasure.",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg",
    stock: 25,
  },
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    price: 450,
    description: "A gripping, heart-wrenching tale of racial injustice in the Deep South, seen through the eyes of young Scout Finch.",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780061120084-L.jpg",
    stock: 20,
  },
  {
    title: "1984",
    author: "George Orwell",
    price: 350,
    description: "A dystopian masterpiece about totalitarianism, surveillance, and the terrifying power of propaganda in a world gone mad.",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
    stock: 30,
  },
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    price: 320,
    description: "The quintessential American novel exploring themes of wealth, class, love, and the elusiveness of the American Dream in the Roaring Twenties.",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg",
    stock: 18,
  },
  {
    title: "One Hundred Years of Solitude",
    author: "Gabriel García Márquez",
    price: 520,
    description: "A landmark novel that chronicles seven generations of the Buendía family in the mythical town of Macondo.",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780060883287-L.jpg",
    stock: 15,
  },
  {
    title: "Brave New World",
    author: "Aldous Huxley",
    price: 380,
    description: "A darkly satirical vision of a utopian future where humans are genetically bred and pharmaceutically conditioned to serve a ruling order.",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780060850524-L.jpg",
    stock: 22,
  },
  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    price: 340,
    description: "The iconic novel of teenage alienation and rebellion as experienced by the unforgettable Holden Caulfield.",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780316769488-L.jpg",
    stock: 20,
  },
  {
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    price: 420,
    description: "A penetrating psychological study of a young man who commits murder and is tormented by guilt and paranoia.",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780486415871-L.jpg",
    stock: 16,
  },
  {
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    price: 460,
    description: "A powerful story of friendship, betrayal, and redemption set against the backdrop of a changing Afghanistan.",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9781594631931-L.jpg",
    stock: 24,
  },
  {
    title: "Norwegian Wood",
    author: "Haruki Murakami",
    price: 490,
    description: "A nostalgic story of loss and sexuality set in 1960s Tokyo, blending melancholy and beauty in Murakami's distinctive style.",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780375704024-L.jpg",
    stock: 18,
  },

  // ─── Non-Fiction ───────────────────────────────────────────
  {
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    price: 599,
    description: "A sweeping narrative of human history from the Stone Age to the Silicon Age, exploring what makes us truly human.",
    category: "Non-Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg",
    stock: 28,
  },
  {
    title: "Educated",
    author: "Tara Westover",
    price: 480,
    description: "An unforgettable memoir about a young woman who leaves her survivalist family and goes on to earn a PhD from Cambridge University.",
    category: "Non-Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780399590504-L.jpg",
    stock: 20,
  },
  {
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    price: 550,
    description: "Nobel laureate Daniel Kahneman's landmark work on the two systems that drive the way we think — intuitive and deliberate.",
    category: "Non-Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780374533557-L.jpg",
    stock: 15,
  },
  {
    title: "The Power of Habit",
    author: "Charles Duhigg",
    price: 420,
    description: "A fascinating exploration of why habits exist and how they can be changed, drawing on cutting-edge neuroscience.",
    category: "Non-Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780812981605-L.jpg",
    stock: 22,
  },
  {
    title: "Guns, Germs, and Steel",
    author: "Jared Diamond",
    price: 580,
    description: "A Pulitzer Prize-winning account of how geography and environment shaped the fates of human societies.",
    category: "Non-Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780393317558-L.jpg",
    stock: 14,
  },

  // ─── Self-Help ─────────────────────────────────────────────
  {
    title: "Atomic Habits",
    author: "James Clear",
    price: 499,
    description: "A revolutionary guide to building good habits and breaking bad ones, with proven strategies backed by science.",
    category: "Self-Help",
    image: "https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg",
    stock: 35,
  },
  {
    title: "Deep Work",
    author: "Cal Newport",
    price: 450,
    description: "Rules for focused success in a distracted world — learn to cultivate the ability to focus without distraction.",
    category: "Self-Help",
    image: "https://covers.openlibrary.org/b/isbn/9781455586691-L.jpg",
    stock: 20,
  },
  {
    title: "The 7 Habits of Highly Effective People",
    author: "Stephen R. Covey",
    price: 520,
    description: "A timeless classic on personal change and effectiveness, offering a principle-centered approach for solving personal and professional problems.",
    category: "Self-Help",
    image: "https://covers.openlibrary.org/b/isbn/9781982137274-L.jpg",
    stock: 25,
  },
  {
    title: "Ikigai",
    author: "Héctor García & Francesc Miralles",
    price: 350,
    description: "The Japanese secret to a long and happy life — discover your purpose and find joy in everyday moments.",
    category: "Self-Help",
    image: "https://covers.openlibrary.org/b/isbn/9780143130727-L.jpg",
    stock: 30,
  },
  {
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    price: 399,
    description: "A counterintuitive approach to living a good life by learning to focus on what truly matters.",
    category: "Self-Help",
    image: "https://covers.openlibrary.org/b/isbn/9780062457714-L.jpg",
    stock: 28,
  },
  {
    title: "Man's Search for Meaning",
    author: "Viktor E. Frankl",
    price: 350,
    description: "A psychiatrist's memoir of life in Nazi death camps and its lessons for spiritual survival, arguing that meaning is the primary drive in life.",
    category: "Self-Help",
    image: "https://covers.openlibrary.org/b/isbn/9780807014271-L.jpg",
    stock: 20,
  },
  {
    title: "The Power of Now",
    author: "Eckhart Tolle",
    price: 420,
    description: "A guide to spiritual enlightenment that shows you how to live in the present moment and free yourself from pain.",
    category: "Self-Help",
    image: "https://covers.openlibrary.org/b/isbn/9781577314806-L.jpg",
    stock: 18,
  },

  // ─── Technology ────────────────────────────────────────────
  {
    title: "Clean Code",
    author: "Robert C. Martin",
    price: 699,
    description: "A handbook of agile software craftsmanship that teaches you how to write code that is clean, well-structured, and maintainable.",
    category: "Technology",
    image: "https://covers.openlibrary.org/b/isbn/9780132350884-L.jpg",
    stock: 15,
  },
  {
    title: "The Pragmatic Programmer",
    author: "David Thomas & Andrew Hunt",
    price: 750,
    description: "A classic guide for software developers that covers everything from personal responsibility to architectural techniques.",
    category: "Technology",
    image: "https://covers.openlibrary.org/b/isbn/9780135957059-L.jpg",
    stock: 12,
  },
  {
    title: "Designing Data-Intensive Applications",
    author: "Martin Kleppmann",
    price: 850,
    description: "The definitive guide to the big ideas behind reliable, scalable, and maintainable data systems.",
    category: "Technology",
    image: "https://covers.openlibrary.org/b/isbn/9781449373320-L.jpg",
    stock: 10,
  },
  {
    title: "You Don't Know JS Yet",
    author: "Kyle Simpson",
    price: 550,
    description: "A deep dive into the core mechanisms of JavaScript that goes beyond syntax to explain how the language really works.",
    category: "Technology",
    image: "https://covers.openlibrary.org/b/isbn/9781491924464-L.jpg",
    stock: 18,
  },
  {
    title: "Cracking the Coding Interview",
    author: "Gayle Laakmann McDowell",
    price: 680,
    description: "189 programming questions and solutions, plus advice on how to succeed in technical interviews at top tech companies.",
    category: "Technology",
    image: "https://covers.openlibrary.org/b/isbn/9780984782857-L.jpg",
    stock: 20,
  },
  {
    title: "Introduction to Algorithms",
    author: "Thomas H. Cormen",
    price: 950,
    description: "The comprehensive textbook on algorithms, covering a broad range of algorithms in depth while remaining accessible.",
    category: "Technology",
    image: "https://covers.openlibrary.org/b/isbn/9780262033848-L.jpg",
    stock: 8,
  },

  // ─── Finance ───────────────────────────────────────────────
  {
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    price: 450,
    description: "What the rich teach their kids about money that the poor and middle class do not — a personal finance classic.",
    category: "Finance",
    image: "https://covers.openlibrary.org/b/isbn/9781612680194-L.jpg",
    stock: 30,
  },
  {
    title: "The Intelligent Investor",
    author: "Benjamin Graham",
    price: 620,
    description: "The definitive book on value investing, praised by Warren Buffett as 'the best book on investing ever written.'",
    category: "Finance",
    image: "https://covers.openlibrary.org/b/isbn/9780060555665-L.jpg",
    stock: 16,
  },
  {
    title: "The Psychology of Money",
    author: "Morgan Housel",
    price: 480,
    description: "Timeless lessons on wealth, greed, and happiness — exploring the strange ways people think about money.",
    category: "Finance",
    image: "https://covers.openlibrary.org/b/isbn/9780857197689-L.jpg",
    stock: 25,
  },
  {
    title: "Think and Grow Rich",
    author: "Napoleon Hill",
    price: 350,
    description: "The timeless classic on the principles of success, based on interviews with over 500 successful individuals.",
    category: "Finance",
    image: "https://covers.openlibrary.org/b/isbn/9781585424337-L.jpg",
    stock: 22,
  },
  {
    title: "The Richest Man in Babylon",
    author: "George S. Clason",
    price: 299,
    description: "Ancient Babylonian parables that reveal timeless truths about building wealth and managing personal finances.",
    category: "Finance",
    image: "https://covers.openlibrary.org/b/isbn/9780451205360-L.jpg",
    stock: 28,
  },

  // ─── Biography ─────────────────────────────────────────────
  {
    title: "Steve Jobs",
    author: "Walter Isaacson",
    price: 650,
    description: "The exclusive biography of Steve Jobs, based on more than forty interviews with the Apple co-founder, as well as with family and colleagues.",
    category: "Biography",
    image: "https://covers.openlibrary.org/b/isbn/9781451648539-L.jpg",
    stock: 15,
  },
  {
    title: "Becoming",
    author: "Michelle Obama",
    price: 580,
    description: "An intimate, powerful memoir by the former First Lady, chronicling her roots and her journey to the White House.",
    category: "Biography",
    image: "https://covers.openlibrary.org/b/isbn/9781524763138-L.jpg",
    stock: 20,
  },
  {
    title: "The Diary of a Young Girl",
    author: "Anne Frank",
    price: 320,
    description: "The hauntingly eloquent diary of a Jewish teenager hiding from the Nazis during World War II — a timeless testament to the human spirit.",
    category: "Biography",
    image: "https://covers.openlibrary.org/b/isbn/9780553296983-L.jpg",
    stock: 25,
  },
  {
    title: "Long Walk to Freedom",
    author: "Nelson Mandela",
    price: 550,
    description: "The autobiography of one of the great moral and political leaders of our time, tracing his life from childhood through his presidency.",
    category: "Biography",
    image: "https://covers.openlibrary.org/b/isbn/9780316548182-L.jpg",
    stock: 14,
  },
  {
    title: "Wings of Fire",
    author: "A.P.J. Abdul Kalam",
    price: 350,
    description: "An autobiography of India's 'Missile Man' and former President, charting his journey from a humble background to leading India's space program.",
    category: "Biography",
    image: "https://covers.openlibrary.org/b/isbn/9788173711466-L.jpg",
    stock: 30,
  },
  {
    title: "Einstein: His Life and Universe",
    author: "Walter Isaacson",
    price: 620,
    description: "A comprehensive biography of Albert Einstein, revealing how his scientific imagination sprang from the rebellious nature of his personality.",
    category: "Biography",
    image: "https://covers.openlibrary.org/b/isbn/9780743264747-L.jpg",
    stock: 12,
  },

  // ─── More Fiction ──────────────────────────────────────────
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    price: 299,
    description: "The beloved classic of wit and romance, following Elizabeth Bennet as she navigates love, class, and society in Regency-era England.",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
    stock: 22,
  },
  {
    title: "The Book Thief",
    author: "Markus Zusak",
    price: 440,
    description: "Narrated by Death, this is the story of a young girl in Nazi Germany who finds solace in stealing books and sharing them with others.",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780375842207-L.jpg",
    stock: 19,
  },
  {
    title: "Dune",
    author: "Frank Herbert",
    price: 520,
    description: "The epic science fiction masterpiece set on the desert planet Arrakis, a tale of politics, religion, and ecology on a grand scale.",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780441172719-L.jpg",
    stock: 16,
  },
  {
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    price: 799,
    description: "The greatest fantasy epic ever told — follow Frodo Baggins on his perilous quest to destroy the One Ring in the fires of Mount Doom.",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780618640157-L.jpg",
    stock: 14,
  },

  // ─── More Non-Fiction ──────────────────────────────────────
  {
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    price: 480,
    description: "A landmark volume in science writing by one of the great minds of our time, exploring black holes, the Big Bang, and the nature of time.",
    category: "Non-Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780553380163-L.jpg",
    stock: 18,
  },
  {
    title: "Outliers",
    author: "Malcolm Gladwell",
    price: 420,
    description: "The story of success — why some people achieve so much more than others, unveiling the hidden factors behind extraordinary achievement.",
    category: "Non-Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780316017930-L.jpg",
    stock: 22,
  },

  // ─── More Self-Help ────────────────────────────────────────
  {
    title: "How to Win Friends and Influence People",
    author: "Dale Carnegie",
    price: 380,
    description: "The all-time classic on human relations — timeless techniques for handling people, winning friends, and influencing others.",
    category: "Self-Help",
    image: "https://covers.openlibrary.org/b/isbn/9780671027032-L.jpg",
    stock: 25,
  },
  {
    title: "Mindset: The New Psychology of Success",
    author: "Carol S. Dweck",
    price: 440,
    description: "Discover how adopting a growth mindset can transform your life, relationships, and career.",
    category: "Self-Help",
    image: "https://covers.openlibrary.org/b/isbn/9780345472328-L.jpg",
    stock: 20,
  },

  // ─── More Finance ──────────────────────────────────────────
  {
    title: "The 4-Hour Workweek",
    author: "Timothy Ferriss",
    price: 460,
    description: "Escape the 9-5, live anywhere, and join the new rich — a revolutionary guide to lifestyle design and automation.",
    category: "Finance",
    image: "https://covers.openlibrary.org/b/isbn/9780307465351-L.jpg",
    stock: 18,
  },

  // ─── More Technology ───────────────────────────────────────
  {
    title: "The Mythical Man-Month",
    author: "Frederick P. Brooks Jr.",
    price: 580,
    description: "The classic essays on software engineering — exploring why adding more people to a late project makes it later.",
    category: "Technology",
    image: "https://covers.openlibrary.org/b/isbn/9780201835953-L.jpg",
    stock: 10,
  },

  // ─── Extra Fiction ──────────────────────────────────────────
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    price: 450,
    description: "The prelude to The Lord of the Rings, following Bilbo Baggins on an unexpected journey to reclaim a lost treasure.",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780618260300-L.jpg",
    stock: 20,
  },
  {
    title: "The Da Vinci Code",
    author: "Dan Brown",
    price: 399,
    description: "A fast-paced thriller involving secret societies, ancient symbols, and a conspiracy that could change history.",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780307474278-L.jpg",
    stock: 25,
  },
  {
    title: "Life of Pi",
    author: "Yann Martel",
    price: 350,
    description: "An extraordinary adventure of a boy stranded on a lifeboat with a Bengal tiger in the middle of the Pacific Ocean.",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780156027328-L.jpg",
    stock: 18,
  },

  {
    title: "Les Misérables",
    author: "Victor Hugo",
    price: 599,
    description: "An epic tale of love, revolution, and redemption in 19th-century France, following Jean Valjean's struggle for justice.",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780451419439-L.jpg",
    stock: 12,
  },
  {
    title: "War and Peace",
    author: "Leo Tolstoy",
    price: 650,
    description: "A monumental novel depicting Russian society during the Napoleonic era, exploring themes of war, peace, and human destiny.",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780307266934-L.jpg",
    stock: 10,
  },
  {
    title: "The Odyssey",
    author: "Homer",
    price: 320,
    description: "The classic Greek epic following Odysseus on his ten-year journey home after the Trojan War.",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780140268867-L.jpg",
    stock: 15,
  },
  {
    title: "Jane Eyre",
    author: "Charlotte Brontë",
    price: 340,
    description: "A powerful story of an orphan girl's journey to independence and her complicated love for the mysterious Mr. Rochester.",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780141441146-L.jpg",
    stock: 20,
  },
  {
    title: "Wuthering Heights",
    author: "Emily Brontë",
    price: 340,
    description: "A dark and passionate tale of love and revenge on the wild Yorkshire moors, centered on Catherine and Heathcliff.",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780141439556-L.jpg",
    stock: 18,
  },
  {
    title: "Frankenstein",
    author: "Mary Shelley",
    price: 280,
    description: "The foundational gothic novel about a scientist who creates life, only to be haunted by his monstrous creation.",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780141439471-L.jpg",
    stock: 22,
  },
  {
    title: "Dracula",
    author: "Bram Stoker",
    price: 320,
    description: "The classic vampire novel following Count Dracula's attempt to move from Transylvania to England to find new blood.",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780141439846-L.jpg",
    stock: 15,
  },
  {
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    price: 310,
    description: "A philosophical novel about a man who remains youthful while his portrait ages and reflects his moral decay.",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780141439570-L.jpg",
    stock: 20,
  },

  // ─── Extra Non-Fiction ─────────────────────────────────────
  {
    title: "The Immortal Life of Henrietta Lacks",
    author: "Rebecca Skloot",
    price: 499,
    description: "The true story of the woman whose cells were taken without her knowledge and became one of the most important tools in medicine.",
    category: "Non-Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9781400052189-L.jpg",
    stock: 25,
  },
  {
    title: "Quiet",
    author: "Susan Cain",
    price: 450,
    description: "A deep dive into the power of introverts in a world that can't stop talking, showing how much we lose by undervaluing them.",
    category: "Non-Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780307352156-L.jpg",
    stock: 22,
  },
  {
    title: "Into the Wild",
    author: "Jon Krakauer",
    price: 380,
    description: "The gripping true story of Christopher McCandless, who walked into the Alaskan wilderness to live off the land.",
    category: "Non-Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780385486804-L.jpg",
    stock: 18,
  },
  {
    title: "The Sixth Extinction",
    author: "Elizabeth Kolbert",
    price: 480,
    description: "A major work on the environmental crisis, exploring how human activity is causing the sixth mass extinction in Earth's history.",
    category: "Non-Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9781250062185-L.jpg",
    stock: 15,
  },
  {
    title: "Bad Blood",
    author: "John Carreyrou",
    price: 520,
    description: "The full inside story of the breathtaking rise and shocking collapse of Theranos, the multibillion-dollar biotech startup.",
    category: "Non-Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9781524731656-L.jpg",
    stock: 20,
  },
  {
    title: "The Emperor of All Maladies",
    author: "Siddhartha Mukherjee",
    price: 650,
    description: "A magnificent, profoundly humane 'biography' of cancer — from its first documented appearances to modern treatments.",
    category: "Non-Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9781439107959-L.jpg",
    stock: 14,
  },
  {
    title: "Cosmos",
    author: "Carl Sagan",
    price: 420,
    description: "A breathtaking exploration of the universe, science, and the human quest for knowledge, based on the legendary TV series.",
    category: "Non-Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780345331359-L.jpg",
    stock: 25,
  },

  // ─── Extra Self-Help ───────────────────────────────────────
  {
    title: "Daring Greatly",
    author: "Brené Brown",
    price: 460,
    description: "Learn how the courage to be vulnerable transforms the way we live, love, parent, and lead.",
    category: "Self-Help",
    image: "https://covers.openlibrary.org/b/isbn/9781592408412-L.jpg",
    stock: 28,
  },
  {
    title: "Grit",
    author: "Angela Duckworth",
    price: 480,
    description: "Psychologist Angela Duckworth shows that the secret to outstanding achievement is not talent but a special blend of passion and persistence.",
    category: "Self-Help",
    image: "https://covers.openlibrary.org/b/isbn/9781501111105-L.jpg",
    stock: 24,
  },
  {
    title: "Flow",
    author: "Mihaly Csikszentmihalyi",
    price: 399,
    description: "The classic work on how to achieve the state of 'flow' — complete absorption in an activity for optimal experience and happiness.",
    category: "Self-Help",
    image: "https://covers.openlibrary.org/b/isbn/9780061339202-L.jpg",
    stock: 18,
  },
  {
    title: "Essentialism",
    author: "Greg McKeown",
    price: 450,
    description: "The disciplined pursuit of less — learn how to identify what is absolutely essential and eliminate everything else.",
    category: "Self-Help",
    image: "https://covers.openlibrary.org/b/isbn/9780804137386-L.jpg",
    stock: 22,
  },
  {
    title: "The Daily Stoic",
    author: "Ryan Holiday",
    price: 420,
    description: "366 days of Stoic insights and exercises to help you find serenity, self-knowledge, and resilience in modern life.",
    category: "Self-Help",
    image: "https://covers.openlibrary.org/b/isbn/9780735214170-L.jpg",
    stock: 35,
  },
  {
    title: "Digital Minimalism",
    author: "Cal Newport",
    price: 440,
    description: "A practical guide to choosing a focused life in a noisy world, focusing on intentional use of technology.",
    category: "Self-Help",
    image: "https://covers.openlibrary.org/b/isbn/9780525536512-L.jpg",
    stock: 20,
  },
  {
    title: "Start with Why",
    author: "Simon Sinek",
    price: 399,
    description: "Discover how great leaders inspire everyone to take action by starting with the most important question: Why?",
    category: "Self-Help",
    image: "https://covers.openlibrary.org/b/isbn/9781591846444-L.jpg",
    stock: 26,
  },
  {
    title: "Can't Hurt Me",
    author: "David Goggins",
    price: 550,
    description: "Master your mind and defy the odds — the incredible true story of David Goggins' journey from trauma to Navy SEAL.",
    category: "Self-Help",
    image: "https://covers.openlibrary.org/b/isbn/9781544512280-L.jpg",
    stock: 30,
  },
  {
    title: "The 48 Laws of Power",
    author: "Robert Greene",
    price: 520,
    description: "Amoral, cunning, ruthless, and instructive, this multi-million-copy New York Times bestseller is the definitive manual for anyone interested in gaining, observing, or defending against ultimate control.",
    category: "Self-Help",
    image: "https://covers.openlibrary.org/b/isbn/9780140280197-L.jpg",
    stock: 15,
  },

  // ─── Extra Technology ──────────────────────────────────────
  {
    title: "Code Complete",
    author: "Steve McConnell",
    price: 799,
    description: "A practical handbook of software construction, covering the most effective techniques and must-know principles for developers.",
    category: "Technology",
    image: "https://covers.openlibrary.org/b/isbn/9780735619678-L.jpg",
    stock: 12,
  },
  {
    title: "Refactoring",
    author: "Martin Fowler",
    price: 720,
    description: "The definitive guide to improving the design of existing code, with a comprehensive catalog of refactorings and examples.",
    category: "Technology",
    image: "https://covers.openlibrary.org/b/isbn/9780134757599-L.jpg",
    stock: 14,
  },
  {
    title: "Patterns of Enterprise Application Architecture",
    author: "Martin Fowler",
    price: 750,
    description: "Learn how to build enterprise-scale applications using proven patterns for data mapping, concurrency, and session state.",
    category: "Technology",
    image: "https://covers.openlibrary.org/b/isbn/9780321127426-L.jpg",
    stock: 10,
  },
  {
    title: "Head First Design Patterns",
    author: "Eric Freeman & Elisabeth Robson",
    price: 680,
    description: "A visually rich guide to software design patterns, making complex architectural concepts easy to understand and apply.",
    category: "Technology",
    image: "https://covers.openlibrary.org/b/isbn/9780596007126-L.jpg",
    stock: 18,
  },
  {
    title: "Soft Skills",
    author: "John Sonmez",
    price: 520,
    description: "The software developer's life manual — covering career, productivity, personal branding, and fitness.",
    category: "Technology",
    image: "https://covers.openlibrary.org/b/isbn/9781617292392-L.jpg",
    stock: 20,
  },
  {
    title: "Zero to One",
    author: "Peter Thiel",
    price: 499,
    description: "Notes on startups, or how to build the future — exploring how to create truly new things that move the world from 0 to 1.",
    category: "Technology",
    image: "https://covers.openlibrary.org/b/isbn/9780804139298-L.jpg",
    stock: 25,
  },
  {
    title: "The Lean Startup",
    author: "Eric Ries",
    price: 450,
    description: "How today's entrepreneurs use continuous innovation to create radically successful businesses.",
    category: "Technology",
    image: "https://covers.openlibrary.org/b/isbn/9780307887894-L.jpg",
    stock: 22,
  },
  {
    title: "Clean Architecture",
    author: "Robert C. Martin",
    price: 720,
    description: "A craftsman's guide to software structure and design, presenting the universal rules of software architecture.",
    category: "Technology",
    image: "https://covers.openlibrary.org/b/isbn/9780134494166-L.jpg",
    stock: 15,
  },

  // ─── Extra Finance ─────────────────────────────────────────
  {
    title: "The Millionaire Next Door",
    author: "Thomas J. Stanley",
    price: 399,
    description: "The surprising secrets of America's wealthy — learn the simple habits that actually build long-term wealth.",
    category: "Finance",
    image: "https://covers.openlibrary.org/b/isbn/9781589795471-L.jpg",
    stock: 20,
  },
  {
    title: "Your Money or Your Life",
    author: "Vicki Robin",
    price: 450,
    description: "9 steps to transforming your relationship with money and achieving financial independence.",
    category: "Finance",
    image: "https://covers.openlibrary.org/b/isbn/9780143115762-L.jpg",
    stock: 18,
  },
  {
    title: "I Will Teach You to Be Rich",
    author: "Ramit Sethi",
    price: 480,
    description: "A 6-week program that works — automated personal finance for people who want to live a rich life.",
    category: "Finance",
    image: "https://covers.openlibrary.org/b/isbn/9781523505746-L.jpg",
    stock: 30,
  },
  {
    title: "The Little Book of Common Sense Investing",
    author: "John C. Bogle",
    price: 420,
    description: "The only way to guarantee your fair share of stock market returns, by the founder of Vanguard.",
    category: "Finance",
    image: "https://covers.openlibrary.org/b/isbn/9780470102107-L.jpg",
    stock: 25,
  },
  {
    title: "The Total Money Makeover",
    author: "Dave Ramsey",
    price: 460,
    description: "A proven plan for financial fitness — learn how to pay off debt and build wealth with Ramsey's baby steps.",
    category: "Finance",
    image: "https://covers.openlibrary.org/b/isbn/9781595555274-L.jpg",
    stock: 22,
  },

  // ─── Extra Biography ───────────────────────────────────────
  {
    title: "Elon Musk",
    author: "Ashlee Vance",
    price: 599,
    description: "Tesla, SpaceX, and the quest for a fantastic future — the first inside look at the life and times of Silicon Valley's most audacious entrepreneur.",
    category: "Biography",
    image: "https://covers.openlibrary.org/b/isbn/9780062301239-L.jpg",
    stock: 20,
  },
  {
    title: "Leonardo da Vinci",
    author: "Walter Isaacson",
    price: 680,
    description: "A masterly biography of history's most creative genius, revealing how he combined art and science to understand the world.",
    category: "Biography",
    image: "https://covers.openlibrary.org/b/isbn/9781501139154-L.jpg",
    stock: 12,
  },
  {
    title: "Shoe Dog",
    author: "Phil Knight",
    price: 520,
    description: "A memoir by the creator of Nike, sharing the inside story of the company's early days as an intrepid startup and its evolution into one of the world's most iconic brands.",
    category: "Biography",
    image: "https://covers.openlibrary.org/b/isbn/9781501135910-L.jpg",
    stock: 25,
  },
  {
    title: "Open",
    author: "Andre Agassi",
    price: 480,
    description: "A captivating memoir by the tennis legend, revealing the high stakes and deep loneliness of a life at the top of the game.",
    category: "Biography",
    image: "https://covers.openlibrary.org/b/isbn/9780307268198-L.jpg",
    stock: 18,
  },
  {
    title: "Total Recall",
    author: "Arnold Schwarzenegger",
    price: 550,
    description: "The unbelievably true story of Arnold Schwarzenegger's life — from bodybuilding to Hollywood to politics.",
    category: "Biography",
    image: "https://covers.openlibrary.org/b/isbn/9781451662436-L.jpg",
    stock: 15,
  },
  {
    title: "Grinding It Out",
    author: "Ray Kroc",
    price: 420,
    description: "The making of McDonald's — the story of Ray Kroc and how he built the world's most successful fast-food chain.",
    category: "Biography",
    image: "https://covers.openlibrary.org/b/isbn/9780312929879-L.jpg",
    stock: 22,
  },


  // ─── Classic Literature ────────────────────────────────────
  {
    title: "Alice's Adventures in Wonderland",
    author: "Lewis Carroll",
    price: 250,
    description: "The classic tale of Alice falling down a rabbit hole into a world of pure nonsense and wonder.",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780141439761-L.jpg",
    stock: 30,
  },
  {
    title: "Gulliver's Travels",
    author: "Jonathan Swift",
    price: 280,
    description: "A biting satire of human nature and society, following Lemuel Gulliver's voyages to strange and fantastic lands.",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780141439495-L.jpg",
    stock: 20,
  },
  {
    title: "Treasure Island",
    author: "Robert Louis Stevenson",
    price: 299,
    description: "The classic pirate adventure featuring Jim Hawkins and the unforgettable Long John Silver.",
    category: "Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780141439600-L.jpg",
    stock: 25,
  },
  {
    title: "The Art of War",
    author: "Sun Tzu",
    price: 199,
    description: "Ancient Chinese military treatise attributed to Sun Tzu, a classic work on strategy and tactics that remains influential today.",
    category: "Non-Fiction",
    image: "https://covers.openlibrary.org/b/isbn/9780195014761-L.jpg",
    stock: 50,
  },
  {
    title: "Meditations",
    author: "Marcus Aurelius",
    price: 350,
    description: "A series of personal writings by the Roman Emperor Marcus Aurelius, offering Stoic philosophy for everyday life.",
    category: "Self-Help",
    image: "https://covers.openlibrary.org/b/isbn/9780140449334-L.jpg",
    stock: 40,
  },
];

const seedData = async () => {
  try {
    await Book.deleteMany();
    await Book.insertMany(books);
    console.log(`✓ Seeded ${books.length} books across multiple categories`);
    process.exit();
  } catch (err) {
    console.error("Seed error:", err.message);
    process.exit(1);
  }
};

seedData();